In [1]:
pip install folium

Requirement already satisfied: folium in /opt/conda/lib/python3.11/site-packages (0.19.4)
Requirement already satisfied: branca>=0.6.0 in /opt/conda/lib/python3.11/site-packages (from folium) (0.8.1)
Requirement already satisfied: jinja2>=2.9 in /opt/conda/lib/python3.11/site-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (from folium) (2.0.2)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /opt/conda/lib/python3.11/site-packages (from folium) (2024.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2>=2.9->folium) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->folium) (2024.12.14)
Note: you may need to restart the kernel to use updated packages.

In [27]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
from shapely import wkt

In [5]:
# Load the bus route data
bus_data = pd.read_csv('stop ids with time diff and location2.csv')
# Check for NaN values in the location columns
bus_data = bus_data.dropna(subset=['stop_lat_1', 'stop_lon_1'])

In [6]:
bus_data

,stop_id_1,stop_id_2,route_id,time_difference,stop_lat_1,stop_lon_1,stop_lat_2,stop_lon_2,School Name,School Latitude,School Longitude,Stop Latitude,Stop Longitude,Distance (miles),Route Numbers
0,390,3388,28,0 days 00:10:22.842105263,37.721190,-122.475153,37.747152,-122.475834,"Lincoln, Abraham Lincoln High School",37.746594,-122.480240,37.747152,-122.475834,0.244338,['28' '91']
1,390,5459,28,0 days 00:43:51,37.721190,-122.475153,NaN,NaN,Galileo High School,37.803791,-122.424149,37.805633,-122.420467,0.238189,['28' '30' '91']
2,390,5469,28,0 days 00:43:00,37.721190,-122.475153,37.805241,-122.423494,Galileo High School,37.803791,-122.424149,37.805241,-122.423494,0.106232,['19' '28' '30' '91']
3,390,6800,28,0 days 00:41:22,37.721190,-122.475153,37.802580,-122.424640,Galileo High School,37.803791,-122.424149,37.802580,-122.424640,0.087735,['28' '49' '90' '91']
4,390,6806,28,0 days 00:42:12,37.721190,-122.475153,37.804287,-122.424996,Galileo High School,37.803791,-122.424149,37.804287,-122.424996,0.057606,['28' '30' '49' '90' '91']
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3092,8159,5338,29,0 days 00:35:05.785714285,37.745838,-122.494810,NaN,NaN,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.720926,-122.403124,0.192761,['29']
3093,8159,5340,29,0 days 00:33:40.928571428,37.745838,-122.494810,37.719376,-122.409058,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.719376,-122.409058,0.202978,['29' '56']
3094,8159,5341,29,0 days 00:34:52,37.745838,-122.494810,37.720677,-122.404098,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.720677,-122.404098,0.147341,['29']
3095,8159,5344,29,0 days 00:34:08.928571428,37.745838,-122.494810,37.719892,-122.407088,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.719892,-122.407088,0.117749,['29' '56']
3096,8159,5351,29,0 days 00:34:37.857142857,37.745838,-122.494810,37.720418,-122.405094,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.720418,-122.405094,0.111615,['29' '56']

In [34]:
# Create a GeoDataFrame for stops
geometry = [Point(xy) for xy in zip(bus_data['stop_lat_1'], bus_data['stop_lon_1'])]
stops_gdf = gpd.GeoDataFrame(bus_data, geometry=geometry)

In [35]:
stops_gdf

,stop_id_1,stop_id_2,route_id,time_difference,stop_lat_1,stop_lon_1,stop_lat_2,stop_lon_2,School Name,School Latitude,School Longitude,Stop Latitude,Stop Longitude,Distance (miles),Route Numbers,geometry
0,390,3388,28,0 days 00:10:22.842105263,37.721190,-122.475153,37.747152,-122.475834,"Lincoln, Abraham Lincoln High School",37.746594,-122.480240,37.747152,-122.475834,0.244338,['28' '91'],POINT (37.721 -122.475)
1,390,5459,28,0 days 00:43:51,37.721190,-122.475153,NaN,NaN,Galileo High School,37.803791,-122.424149,37.805633,-122.420467,0.238189,['28' '30' '91'],POINT (37.721 -122.475)
2,390,5469,28,0 days 00:43:00,37.721190,-122.475153,37.805241,-122.423494,Galileo High School,37.803791,-122.424149,37.805241,-122.423494,0.106232,['19' '28' '30' '91'],POINT (37.721 -122.475)
3,390,6800,28,0 days 00:41:22,37.721190,-122.475153,37.802580,-122.424640,Galileo High School,37.803791,-122.424149,37.802580,-122.424640,0.087735,['28' '49' '90' '91'],POINT (37.721 -122.475)
4,390,6806,28,0 days 00:42:12,37.721190,-122.475153,37.804287,-122.424996,Galileo High School,37.803791,-122.424149,37.804287,-122.424996,0.057606,['28' '30' '49' '90' '91'],POINT (37.721 -122.475)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3092,8159,5338,29,0 days 00:35:05.785714285,37.745838,-122.494810,NaN,NaN,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.720926,-122.403124,0.192761,['29'],POINT (37.746 -122.495)
3093,8159,5340,29,0 days 00:33:40.928571428,37.745838,-122.494810,37.719376,-122.409058,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.719376,-122.409058,0.202978,['29' '56'],POINT (37.746 -122.495)
3094,8159,5341,29,0 days 00:34:52,37.745838,-122.494810,37.720677,-122.404098,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.720677,-122.404098,0.147341,['29'],POINT (37.746 -122.495)
3095,8159,5344,29,0 days 00:34:08.928571428,37.745838,-122.494810,37.719892,-122.407088,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.719892,-122.407088,0.117749,['29' '56'],POINT (37.746 -122.495)
3096,8159,5351,29,0 days 00:34:37.857142857,37.745838,-122.494810,37.720418,-122.405094,"Burton, Phillip And Sala Burton High School",37.721546,-122.406555,37.720418,-122.405094,0.111615,['29' '56'],POINT (37.746 -122.495)

In [7]:
data = bus_data[['stop_id_1', 'time_difference', 'stop_lat_1', 'stop_lon_1', 'route_id', 'School Name']]
data

,stop_id_1,time_difference,stop_lat_1,stop_lon_1,route_id,School Name
0,390,0 days 00:10:22.842105263,37.721190,-122.475153,28,"Lincoln, Abraham Lincoln High School"
1,390,0 days 00:43:51,37.721190,-122.475153,28,Galileo High School
2,390,0 days 00:43:00,37.721190,-122.475153,28,Galileo High School
3,390,0 days 00:41:22,37.721190,-122.475153,28,Galileo High School
4,390,0 days 00:42:12,37.721190,-122.475153,28,Galileo High School
...,...,...,...,...,...,...
3092,8159,0 days 00:35:05.785714285,37.745838,-122.494810,29,"Burton, Phillip And Sala Burton High School"
3093,8159,0 days 00:33:40.928571428,37.745838,-122.494810,29,"Burton, Phillip And Sala Burton High School"
3094,8159,0 days 00:34:52,37.745838,-122.494810,29,"Burton, Phillip And Sala Burton High School"
3095,8159,0 days 00:34:08.928571428,37.745838,-122.494810,29,"Burton, Phillip And Sala Burton High School"
3096,8159,0 days 00:34:37.857142857,37.745838,-122.494810,29,"Burton, Phillip And Sala Burton High School"

In [10]:
censustract=pd.read_csv('Census_2020__Tracts_for_San_Francisco_20250310.csv')

In [11]:
censustract

,the_geom,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,data_loaded_at,data_as_of
0,MULTIPOLYGON (((-122.427223 37.715548999999996...,6,75,980501,6075980501,9805.01,Census Tract 9805.01,G5020,S,1471536,9769,37.716208,-122.419346,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
1,"MULTIPOLYGON (((-122.453206 37.768249, -122.45...",6,75,17102,6075017102,171.02,Census Tract 171.02,G5020,S,294894,0,37.765435,-122.450475,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
2,"MULTIPOLYGON (((-122.414995 37.787454, -122.41...",6,75,12302,6075012302,123.02,Census Tract 123.02,G5020,S,92653,0,37.787022,-122.412097,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
3,"MULTIPOLYGON (((-122.432351 37.773779, -122.43...",6,75,16801,6075016801,168.01,Census Tract 168.01,G5020,S,226534,0,37.771331,-122.429013,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
4,"MULTIPOLYGON (((-122.41246100000001 37.791627,...",6,75,11902,6075011902,119.02,Census Tract 119.02,G5020,S,93053,0,37.790996,-122.409807,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,"MULTIPOLYGON (((-122.426462 37.766272, -122.42...",6,75,20201,6075020201,202.01,Census Tract 202.01,G5020,S,140617,0,37.764788,-122.424095,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
240,MULTIPOLYGON (((-122.393618 37.783077999999996...,6,75,61508,6075061508,615.08,Census Tract 615.08,G5020,S,227943,152297,37.785752,-122.386381,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
241,"MULTIPOLYGON (((-122.430747 37.798648, -122.42...",6,75,13001,6075013001,130.01,Census Tract 130.01,G5020,S,181456,0,37.797663,-122.427228,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
242,"MULTIPOLYGON (((-122.424835 37.802268, -122.42...",6,75,10201,6075010201,102.01,Census Tract 102.01,G5020,S,186873,0,37.801303,-122.421215,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM
243,"MULTIPOLYGON (((-122.42280099999999 37.792161,...",6,75,11101,6075011101,111.01,Census Tract 111.01,G5020,S,121412,0,37.791682,-122.419266,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM

In [38]:
# Assuming the census tract data includes geometry information in WKT format
censustract['geometry'] = censustract['the_geom'].apply(wkt.loads)
tracts_gdf = gpd.GeoDataFrame(censustract, geometry='geometry')

In [39]:
tracts_gdf

,the_geom,STATEFP,COUNTYFP,TRACTCE,GEOID,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,data_loaded_at,data_as_of,geometry
0,MULTIPOLYGON (((-122.427223 37.715548999999996...,6,75,980501,6075980501,9805.01,Census Tract 9805.01,G5020,S,1471536,9769,37.716208,-122.419346,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.42722 37.71555, -122.4271..."
1,"MULTIPOLYGON (((-122.453206 37.768249, -122.45...",6,75,17102,6075017102,171.02,Census Tract 171.02,G5020,S,294894,0,37.765435,-122.450475,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.45321 37.76825, -122.4516..."
2,"MULTIPOLYGON (((-122.414995 37.787454, -122.41...",6,75,12302,6075012302,123.02,Census Tract 123.02,G5020,S,92653,0,37.787022,-122.412097,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.415 37.78745, -122.41335 ..."
3,"MULTIPOLYGON (((-122.432351 37.773779, -122.43...",6,75,16801,6075016801,168.01,Census Tract 168.01,G5020,S,226534,0,37.771331,-122.429013,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.43235 37.77378, -122.4308..."
4,"MULTIPOLYGON (((-122.41246100000001 37.791627,...",6,75,11902,6075011902,119.02,Census Tract 119.02,G5020,S,93053,0,37.790996,-122.409807,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.41246 37.79163, -122.4117..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,"MULTIPOLYGON (((-122.426462 37.766272, -122.42...",6,75,20201,6075020201,202.01,Census Tract 202.01,G5020,S,140617,0,37.764788,-122.424095,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.42646 37.76627, -122.4252..."
240,MULTIPOLYGON (((-122.393618 37.783077999999996...,6,75,61508,6075061508,615.08,Census Tract 615.08,G5020,S,227943,152297,37.785752,-122.386381,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.39362 37.78308, -122.3928..."
241,"MULTIPOLYGON (((-122.430747 37.798648, -122.42...",6,75,13001,6075013001,130.01,Census Tract 130.01,G5020,S,181456,0,37.797663,-122.427228,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.43075 37.79865, -122.4291..."
242,"MULTIPOLYGON (((-122.424835 37.802268, -122.42...",6,75,10201,6075010201,102.01,Census Tract 102.01,G5020,S,186873,0,37.801303,-122.421215,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.42484 37.80227, -122.4246..."
243,"MULTIPOLYGON (((-122.42280099999999 37.792161,...",6,75,11101,6075011101,111.01,Census Tract 111.01,G5020,S,121412,0,37.791682,-122.419266,03/04/2022 12:00:00 AM,02/01/2021 12:00:00 AM,"MULTIPOLYGON (((-122.4228 37.79216, -122.42258..."

In [40]:

# Ensure both GeoDataFrames use the same coordinate reference system (CRS)
stops_gdf = stops_gdf.set_crs('EPSG:4326')
tracts_gdf = tracts_gdf.set_crs('EPSG:4326')

In [41]:
# Perform a spatial join
mapped_data = gpd.sjoin(stops_gdf, tracts_gdf, how='left', predicate='within')

In [42]:
mapped_data

,stop_id_1,stop_id_2,route_id,time_difference,stop_lat_1,stop_lon_1,stop_lat_2,stop_lon_2,School Name,School Latitude,...,NAME,NAMELSAD,MTFCC,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,data_loaded_at,data_as_of
0,390,3388,28,0 days 00:10:22.842105263,37.721190,-122.475153,37.747152,-122.475834,"Lincoln, Abraham Lincoln High School",37.746594,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,390,5459,28,0 days 00:43:51,37.721190,-122.475153,NaN,NaN,Galileo High School,37.803791,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,390,5469,28,0 days 00:43:00,37.721190,-122.475153,37.805241,-122.423494,Galileo High School,37.803791,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,390,6800,28,0 days 00:41:22,37.721190,-122.475153,37.802580,-122.424640,Galileo High School,37.803791,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,390,6806,28,0 days 00:42:12,37.721190,-122.475153,37.804287,-122.424996,Galileo High School,37.803791,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3092,8159,5338,29,0 days 00:35:05.785714285,37.745838,-122.494810,NaN,NaN,"Burton, Phillip And Sala Burton High School",37.721546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3093,8159,5340,29,0 days 00:33:40.928571428,37.745838,-122.494810,37.719376,-122.409058,"Burton, Phillip And Sala Burton High School",37.721546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3094,8159,5341,29,0 days 00:34:52,37.745838,-122.494810,37.720677,-122.404098,"Burton, Phillip And Sala Burton High School",37.721546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3095,8159,5344,29,0 days 00:34:08.928571428,37.745838,-122.494810,37.719892,-122.407088,"Burton, Phillip And Sala Burton High School",37.721546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3096,8159,5351,29,0 days 00:34:37.857142857,37.745838,-122.494810,37.720418,-122.405094,"Burton, Phillip And Sala Burton High School",37.721546,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN