In [58]:
import pandas as pd

def display_schools(file_path, output_path):
    """
    Reads a CSV file, filters out any rows where 'campus name' contains 'Lowell' or 'Ruth Awasa', 
    and writes to a new CSV file.
    :param file_path: Path to the CSV file.
    :param output_path: Path to save the filtered CSV file.
    """
    try:
        # Load the CSV file
        df = pd.read_csv('Schools_20250202.csv')
        
        # Ensure the column name is correct (update if necessary)
        if 'Campus Name' not in df.columns:
            raise ValueError("Column 'campus name' not found in CSV file. Please check the column names.")
        
        # Filter out schools where 'campus name' contains the excluded words
        excluded_keywords = ["Lowell", "Asawa"]
        filtered_df = df[~df['Campus Name'].str.contains('|'.join(excluded_keywords), case=False, na=False)]
        
        # Save to a new CSV file
        filtered_df.to_csv(output_path, index=False)
        
        # Display the remaining schools
        print(filtered_df)
        print(f"Filtered data has been saved to {output_path}")
    except Exception as e:
        print("Error:", e)

# Example usage
if __name__ == "__main__":
    csv_path = "Schools_20250202.csv"  # Path to your uploaded CSV file
    output_csv_path = "Filtered_Schools.csv"  # Path to save the new filtered CSV file
    display_schools(csv_path, output_csv_path)

                                           Campus Name CCSF Entity  \
0                   Milk, Harvey Milk Childrens Center       SFUSD
1                           Mckinley Elementary School       SFUSD
2    Jewish Community Center San Francisco - Rosenb...     Private
3                               Eureka Learning Center     Private
4                       Noriega Early Education School       SFUSD
..                                                 ...         ...
440                      Golden Gate Guppies Preschool     Private
441                                   Lands End School     Private
442                      San Francisco Pacific Academy     Private
443                    Wells, Ida B. Wells High School       SFUSD
444          Munchkinland Preschool And Family Daycare     Private

     Lower Grade  Upper Grade Grade Range               Category Map Label  \
0             -2           -1          PK               USD PreK    CDC095
1              0            5         K-5         USD Grades K-5     PS075
2             -2           -1          PK  Independent / Private    CDC058
3             -2           -1          PK  Independent / Private    CDC035
4             -2            5        PK-5          USD PreK/TK-5     PS085
..           ...          ...         ...                    ...       ...
440           -2           -1          PK  Independent / Private    CDC046
441           -2           -1          PK  Independent / Private    CDC071
442            0            8         K-8  Independent / Private    IND317
443            9           12        9-12        USD Grades 9-12     PS124
444           -2           -1          PK  Independent / Private    CDC110

     Lower Age  Upper Age General Type  ...  \
0            3          4          CDC  ...
1            5         10           PS  ...
2            3          4          CDC  ...
3            3          4          CDC  ...
4            3         10           PS  ...
..         ...        ...          ...  ...
440          3          4          CDC  ...
441          3          4          CDC  ...
442          5         13          IND  ...
443         14         17           PS  ...
444          3          4          CDC  ...

                                        Campus Address Supervisor District  \
0                 841 ELLIS ST, SAN FRANCISCO CA 94117                   6
1                1025 14TH ST, San Francisco, CA 94114                   8
2           325 ARGUELLO BLVD, SAN FRANCISCO, CA 94118                   1
3              464 DIAMOND ST, SAN FRANCISCO, CA 94114                   8
4               1775 44TH AVE, San Francisco, CA 94122                   4
..                                                 ...                 ...
440        2426 CALIFORNIA ST, SAN FRANCISCO, CA 94115                   2
441  4150 CLEMENT ST BLDG T35, SAN FRANCISCO, CA 94121                   1
442            3301 BALBOA ST, SAN FRANCISCO, CA 94121                   1
443             1099 HAYES ST, SAN FRANCISCO, CA 94117                   5
444          4710 CABRILLO ST, SAN FRANCISCO, CA 94121                   1

     County FIPS    County Name                    Location 1  \
0           6075  SAN FRANCISCO  CA\n(37.783802, -122.420105)
1           6075  SAN FRANCISCO  CA\n(37.766884, -122.436279)
2           6075  SAN FRANCISCO  CA\n(37.784588, -122.459488)
3           6075  SAN FRANCISCO  CA\n(37.754967, -122.437004)
4           6075  SAN FRANCISCO  CA\n(37.753834, -122.503654)
..           ...            ...                           ...
440         6075  SAN FRANCISCO  CA\n(37.789124, -122.434509)
441         6075  SAN FRANCISCO  CA\n(37.782593, -122.504578)
442         6075  SAN FRANCISCO  CA\n(37.775639, -122.494286)
443         6075  SAN FRANCISCO  CA\n(37.775013, -122.433899)
444         6075  SAN FRANCISCO  CA\n(37.773445, -122.509254)

    Neighborhoods (old)  Zip Codes  Fire Prevention Districts  \
0                    36      28858                        7.0
1                     3      28862                       15.0
2                    11         54                       11.0
3                    22      28862                        2.0
4                    35         56                        1.0
..                  ...        ...                        ...
440                  27      29490                       13.0
441                  15         55                       11.0
442                  26         55                       11.0
443                  10      29492                       15.0
444                  26         55                       11.0

     Police Districts  Supervisor Districts
0                 9.0                     9
1                 5.0                     5
2                 6.0                     2
3                 4.0                     5
4                 8.0                     3
..                ...                   ...
440               9.0                     1
441               6.0                     2
442               6.0                     2
443               5.0                    11
444               6.0                     2

[443 rows x 21 columns]
Filtered data has been saved to Filtered_Schools.csv

In [59]:
import geopandas as gpd
import folium
from geopy.distance import geodesic

In [60]:
Filtered = gpd.read_file('Filtered_Schools.csv')

In [61]:
Filtered.head()

,Campus Name,CCSF Entity,Lower Grade,Upper Grade,Grade Range,Category,Map Label,Lower Age,Upper Age,General Type,...,Campus Address,Supervisor District,County FIPS,County Name,Location 1,Neighborhoods (old),Zip Codes,Fire Prevention Districts,Police Districts,Supervisor Districts
0,"Milk, Harvey Milk Childrens Center",SFUSD,-2,-1,PK,USD PreK,CDC095,3,4,CDC,...,"841 ELLIS ST, SAN FRANCISCO CA 94117",6,6075,SAN FRANCISCO,"CA\n(37.783802, -122.420105)",36,28858,7.0,9.0,9
1,Mckinley Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS075,5,10,PS,...,"1025 14TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.766884, -122.436279)",3,28862,15.0,5.0,5
2,Jewish Community Center San Francisco - Rosenb...,Private,-2,-1,PK,Independent / Private,CDC058,3,4,CDC,...,"325 ARGUELLO BLVD, SAN FRANCISCO, CA 94118",1,6075,SAN FRANCISCO,"CA\n(37.784588, -122.459488)",11,54,11.0,6.0,2
3,Eureka Learning Center,Private,-2,-1,PK,Independent / Private,CDC035,3,4,CDC,...,"464 DIAMOND ST, SAN FRANCISCO, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.754967, -122.437004)",22,28862,2.0,4.0,5
4,Noriega Early Education School,SFUSD,-2,5,PK-5,USD PreK/TK-5,PS085,3,10,PS,...,"1775 44TH AVE, San Francisco, CA 94122",4,6075,SAN FRANCISCO,"CA\n(37.753834, -122.503654)",35,56,1.0,8.0,3

In [62]:
publicschools = Filtered[Filtered['CCSF Entity'].str.contains('SFUSD')]

In [63]:
publicschools

,Campus Name,CCSF Entity,Lower Grade,Upper Grade,Grade Range,Category,Map Label,Lower Age,Upper Age,General Type,...,Campus Address,Supervisor District,County FIPS,County Name,Location 1,Neighborhoods (old),Zip Codes,Fire Prevention Districts,Police Districts,Supervisor Districts
0,"Milk, Harvey Milk Childrens Center",SFUSD,-2,-1,PK,USD PreK,CDC095,3,4,CDC,...,"841 ELLIS ST, SAN FRANCISCO CA 94117",6,6075,SAN FRANCISCO,"CA\n(37.783802, -122.420105)",36,28858,7.0,9.0,9
1,Mckinley Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS075,5,10,PS,...,"1025 14TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.766884, -122.436279)",3,28862,15.0,5.0,5
4,Noriega Early Education School,SFUSD,-2,5,PK-5,USD PreK/TK-5,PS085,3,10,PS,...,"1775 44TH AVE, San Francisco, CA 94122",4,6075,SAN FRANCISCO,"CA\n(37.753834, -122.503654)",35,56,1.0,8.0,3
10,Sutro Elementary / Early Education,SFUSD,0,5,K-5,USD Grades K-5,PS113,5,10,PS,...,"235 12TH AVE, San Francisco, CA 94118",1,6075,SAN FRANCISCO,"CA\n(37.783604, -122.471451)",11,54,11.0,6.0,2
11,"Marshall, Thurgood Marshall High School",SFUSD,9,12,9-12,USD Grades 9-12,PS073,14,17,PS,...,"45 CONKLING ST, San Francisco, CA 94124",10,6075,SAN FRANCISCO,"CA\n(37.736309, -122.401649)",1,58,10.0,3.0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,Longfellow Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS068,5,10,PS,...,"755 MORSE ST, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.710423, -122.446739)",5,28861,9.0,7.0,6
435,"Webster, Daniel Webster Out-Of-School (OST) Pr...",SFUSD,0,5,K-5,USD Grades K-5,PS123,5,10,PS,...,"465 MISSOURI ST, San Francisco, CA 94107",10,6075,SAN FRANCISCO,"CA\n(37.760521, -122.395843)",29,28856,10.0,3.0,8
436,Mission High School,SFUSD,9,12,9-12,USD Grades 9-12,PS080,14,17,PS,...,"3750 18TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.76202, -122.427307)",3,28862,8.0,4.0,5
437,Miraloma Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS078,5,10,PS,...,"175 OMAR WAY, San Francisco, CA 94127",7,6075,SAN FRANCISCO,"CA\n(37.738636, -122.450188)",40,59,9.0,7.0,4
441,"Wells, Ida B. Wells High School",SFUSD,9,12,9-12,USD Grades 9-12,PS124,14,17,PS,...,"1099 HAYES ST, SAN FRANCISCO, CA 94117",5,6075,SAN FRANCISCO,"CA\n(37.775013, -122.433899)",10,29492,15.0,5.0,11

In [64]:
publichighschools = publicschools[publicschools['Grade Range'].str.contains('9-12')]

In [65]:
publichighschools

,Campus Name,CCSF Entity,Lower Grade,Upper Grade,Grade Range,Category,Map Label,Lower Age,Upper Age,General Type,...,Campus Address,Supervisor District,County FIPS,County Name,Location 1,Neighborhoods (old),Zip Codes,Fire Prevention Districts,Police Districts,Supervisor Districts
11,"Marshall, Thurgood Marshall High School",SFUSD,9,12,9-12,USD Grades 9-12,PS073,14,17,PS,...,"45 CONKLING ST, San Francisco, CA 94124",10,6075,SAN FRANCISCO,"CA\n(37.736309, -122.401649)",1,58,10.0,3.0,8
38,"Hearst, Phoebe Apperson Hearst Home",SFUSD,9,12,9-12,USD Grades 9-12,PS045,14,17,PS,...,"3045 SANTIAGO ST, SAN FRANCISCO 94116",4,6075,SAN FRANCISCO,"CA\n(37.74363, -122.500053)",35,29491,1.0,8.0,3
90,"Burton, Phillip And Sala Burton High School",SFUSD,9,12,9-12,USD Grades 9-12,PS011,14,17,PS,...,"400 MANSELL ST, San Francisco, CA 94134",9,6075,SAN FRANCISCO,"CA\n(37.721546, -122.406555)",28,309,10.0,3.0,7
92,"Washington, George Washington High School",SFUSD,9,12,9-12,USD Grades 9-12,PS121,14,17,PS,...,"600 32ND AVE, San Francisco, CA 94121",1,6075,SAN FRANCISCO,"CA\n(37.777905, -122.491013)",26,55,11.0,6.0,2
135,"Lincoln, Abraham Lincoln High School",SFUSD,9,12,9-12,USD Grades 9-12,PS067,14,17,PS,...,"2162 24TH AVE, San Francisco, CA 94116",4,6075,SAN FRANCISCO,"CA\n(37.746594, -122.48024)",35,29491,1.0,8.0,3
174,Life Learning Academy Charter School,SFUSD,9,12,9-12,USD Charter School,PS064,14,17,PS,...,"651 8TH TI ST, SAN FRANCISCO, CA 94130",6,6075,SAN FRANCISCO,"CA\n(37.825512, -122.367996)",37,62,,2.0,9
194,Gateway High School / Kipp Sf Bay Academy,SFUSD,9,12,9-12,USD Charter School,PS037,14,17,PS,...,"1430 SCOTT ST, San Francisco, CA 94115",5,6075,SAN FRANCISCO,"CA\n(37.783264, -122.436691)",41,29490,13.0,5.0,11
195,Galileo High School,SFUSD,9,12,9-12,USD Grades 9-12,PS035,14,17,PS,...,"1150 FRANCISCO ST, San Francisco, CA 94109",2,6075,SAN FRANCISCO,"CA\n(37.803791, -122.424149)",32,28858,5.0,9.0,1
219,Balboa High School,SFUSD,9,12,9-12,USD Grades 9-12,PS007,14,17,PS,...,"1000 CAYUGA AVE, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.721142, -122.441399)",25,28861,9.0,7.0,6
284,City Arts And Tech High School,SFUSD,9,12,9-12,USD Grades 9-12,PS019,14,17,PS,...,"325 LA GRANDE AVE, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.718784, -122.424667)",18,309,9.0,7.0,6
286,Independence High School,SFUSD,9,12,9-12,USD Grades 9-12,PS049,14,17,PS,...,"1350 07TH AVE, San Francisco, CA 94122",5,6075,SAN FRANCISCO,"CA\n(37.763226, -122.463585)",12,56,1.0,5.0,11
305,"Wallenberg, Raoul Wallenberg High School",SFUSD,9,12,9-12,USD Grades 9-12,PS120,14,17,PS,...,"40 VEGA ST, San Francisco, CA 94118",2,6075,SAN FRANCISCO,"CA\n(37.780647, -122.445953)",16,54,15.0,5.0,1
328,Downtown High School,SFUSD,9,12,9-12,USD Grades 9-12,PS025,14,17,PS,...,"693 VERMONT ST, San Francisco, CA 94107",10,6075,SAN FRANCISCO,"CA\n(37.761398, -122.403702)",29,28856,10.0,3.0,8
331,San Francisco International High School,SFUSD,9,12,9-12,USD Grades 9-12,PS101,14,17,PS,...,"1050 YORK ST, SAN FRANCISCO, CA 94110",9,6075,SAN FRANCISCO,"CA\n(37.75523, -122.408859)",19,28859,2.0,4.0,7
414,"Jordan, June Jordan High School",SFUSD,9,12,9-12,USD Grades 9-12,PS053,14,17,PS,...,"325 LA GRANDE AVE, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.719536, -122.425148)",18,309,9.0,7.0,6
417,"O'Connell, John O'Connell High School",SFUSD,9,12,9-12,USD Grades 9-12,PS086,14,17,PS,...,"2355 FOLSOM ST, San Francisco, CA 94110",9,6075,SAN FRANCISCO,"CA\n(37.759514, -122.413559)",19,28859,2.0,4.0,7
436,Mission High School,SFUSD,9,12,9-12,USD Grades 9-12,PS080,14,17,PS,...,"3750 18TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.76202, -122.427307)",3,28862,8.0,4.0,5
441,"Wells, Ida B. Wells High School",SFUSD,9,12,9-12,USD Grades 9-12,PS124,14,17,PS,...,"1099 HAYES ST, SAN FRANCISCO, CA 94117",5,6075,SAN FRANCISCO,"CA\n(37.775013, -122.433899)",10,29492,15.0,5.0,11

In [66]:
dataframe1 = pd.read_csv("cdenroll2324-v24.csv")

In [67]:
dataframe2 = dataframe1.dropna()

In [68]:
dataframe2

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
272,2023-24,S,1,10017.0,112607.0,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,Y,AR_0418,...,0,0,0,23,11,15,34,36,53,50
273,2023-24,S,1,10017.0,112607.0,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,Y,AR_1922,...,0,0,0,0,0,0,0,0,0,1
274,2023-24,S,1,10017.0,112607.0,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,Y,ELAS_EL,...,*,*,*,*,*,*,*,*,*,15
275,2023-24,S,1,10017.0,112607.0,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,Y,ELAS_EO,...,*,*,*,20,*,*,21,16,26,19
276,2023-24,S,1,10017.0,112607.0,Alameda,Alameda County Office of Education,Envision Academy for Arts & Technology,Y,ELAS_IFEP,...,*,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267757,2023-24,S,58,72769.0,5838305.0,Yuba,Wheatland Union High,Wheatland Union High,N,SG_FS,...,*,*,*,*,*,*,*,*,*,*
267758,2023-24,S,58,72769.0,5838305.0,Yuba,Wheatland Union High,Wheatland Union High,N,SG_HM,...,*,*,*,*,*,*,*,*,*,*
267759,2023-24,S,58,72769.0,5838305.0,Yuba,Wheatland Union High,Wheatland Union High,N,SG_MG,...,*,*,*,*,*,*,*,*,*,*
267760,2023-24,S,58,72769.0,5838305.0,Yuba,Wheatland Union High,Wheatland Union High,N,SG_SD,...,*,*,*,*,*,*,199,200,180,221
267761,2023-24,S,58,72769.0,5838305.0,Yuba,Wheatland Union High,Wheatland Union High,N,TA,...,0,0,0,0,0,0,260,273,244,271

In [69]:
dataframe3 = dataframe2[dataframe2['CountyName'].str.contains('San Francisco')]

In [70]:
dataframe3

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
195771,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,AR_0418,...,0,2,2,1,3,5,8,7,10,26
195772,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,AR_1922,...,0,0,0,0,0,0,0,0,1,15
195773,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,ELAS_EL,...,*,*,*,*,*,*,*,*,*,*
195774,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,ELAS_EO,...,*,*,*,*,*,*,*,*,*,24
195775,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,ELAS_IFEP,...,*,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198665,2023-24,S,38,77131.0,137307.0,San Francisco,SBE - KIPP Bayview Elementary,KIPP Bayview Elementary,Y,SG_EL,...,*,*,*,*,*,*,*,*,*,*
198666,2023-24,S,38,77131.0,137307.0,San Francisco,SBE - KIPP Bayview Elementary,KIPP Bayview Elementary,Y,SG_FS,...,*,*,*,*,*,*,*,*,*,*
198667,2023-24,S,38,77131.0,137307.0,San Francisco,SBE - KIPP Bayview Elementary,KIPP Bayview Elementary,Y,SG_HM,...,*,*,*,*,*,*,*,*,*,*
198668,2023-24,S,38,77131.0,137307.0,San Francisco,SBE - KIPP Bayview Elementary,KIPP Bayview Elementary,Y,SG_SD,...,25,20,*,*,*,*,*,*,*,*
198669,2023-24,S,38,77131.0,137307.0,San Francisco,SBE - KIPP Bayview Elementary,KIPP Bayview Elementary,Y,TA,...,25,22,0,0,0,0,0,0,0,0

In [78]:
dataframe4 = dataframe3[dataframe3['Charter'].str.contains('N')]

In [80]:
dataframe4

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
195771,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,AR_0418,...,0,2,2,1,3,5,8,7,10,26
195772,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,AR_1922,...,0,0,0,0,0,0,0,0,1,15
195773,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,ELAS_EL,...,*,*,*,*,*,*,*,*,*,*
195774,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,ELAS_EO,...,*,*,*,*,*,*,*,*,*,24
195775,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,ELAS_IFEP,...,*,*,*,*,*,*,*,*,*,*
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198539,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,SG_EL,...,17,29,19,*,*,*,*,*,*,*
198540,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,SG_FS,...,*,*,*,*,*,*,*,*,*,*
198541,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,SG_HM,...,*,*,*,*,*,*,*,*,*,*
198542,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,SG_SD,...,32,38,29,*,*,*,*,*,*,*
198543,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,TA,...,37,47,42,0,0,0,0,0,0,0

In [82]:
df_excluded = dataframe4[~dataframe4['GR_09'].str.contains('\*')]
df_excluded

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
195771,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,AR_0418,...,0,2,2,1,3,5,8,7,10,26
195772,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,AR_1922,...,0,0,0,0,0,0,0,0,1,15
195780,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,RE_A,...,0,0,0,0,1,0,2,0,1,13
195781,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,RE_B,...,0,1,0,0,0,2,1,3,2,5
195782,2023-24,S,38,10389.0,1.0,San Francisco,San Francisco County Office of Education,"Nonpublic, Nonsectarian Schools",N,RE_D,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198534,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_H,...,22,20,18,0,0,0,0,0,0,0
198535,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_P,...,0,0,0,0,0,0,0,0,0,0
198536,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_T,...,2,1,2,0,0,0,0,0,0,0
198537,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_W,...,1,8,2,0,0,0,0,0,0,0
198543,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,TA,...,37,47,42,0,0,0,0,0,0,0

In [85]:
dataframe5 = df_excluded[df_excluded['DistrictName'].str.contains('San Francisco Unified')]

In [86]:
dataframe5

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
195965,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,AR_0418,...,0,0,0,0,0,0,0,0,0,0
195972,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_A,...,0,0,0,0,0,0,0,0,0,0
195973,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_B,...,0,0,0,0,0,0,0,0,0,0
195974,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_D,...,0,0,0,0,0,0,0,0,0,0
195975,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_F,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198534,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_H,...,22,20,18,0,0,0,0,0,0,0
198535,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_P,...,0,0,0,0,0,0,0,0,0,0
198536,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_T,...,2,1,2,0,0,0,0,0,0,0
198537,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_W,...,1,8,2,0,0,0,0,0,0,0
198543,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,TA,...,37,47,42,0,0,0,0,0,0,0

In [92]:
dataframe6 = dataframe5[~dataframe5['SchoolName'].str.contains('Elementary')]

In [93]:
dataframe6

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
195965,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,AR_0418,...,0,0,0,0,0,0,0,0,0,0
195972,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_A,...,0,0,0,0,0,0,0,0,0,0
195973,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_B,...,0,0,0,0,0,0,0,0,0,0
195974,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_D,...,0,0,0,0,0,0,0,0,0,0
195975,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_F,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198534,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_H,...,22,20,18,0,0,0,0,0,0,0
198535,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_P,...,0,0,0,0,0,0,0,0,0,0
198536,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_T,...,2,1,2,0,0,0,0,0,0,0
198537,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_W,...,1,8,2,0,0,0,0,0,0,0
198543,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,TA,...,37,47,42,0,0,0,0,0,0,0

In [95]:
dataframe7 = dataframe6[~dataframe6['SchoolName'].str.contains('Middle')]

In [96]:
dataframe7

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
195965,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,AR_0418,...,0,0,0,0,0,0,0,0,0,0
195972,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_A,...,0,0,0,0,0,0,0,0,0,0
195973,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_B,...,0,0,0,0,0,0,0,0,0,0
195974,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_D,...,0,0,0,0,0,0,0,0,0,0
195975,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_F,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198534,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_H,...,22,20,18,0,0,0,0,0,0,0
198535,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_P,...,0,0,0,0,0,0,0,0,0,0
198536,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_T,...,2,1,2,0,0,0,0,0,0,0
198537,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_W,...,1,8,2,0,0,0,0,0,0,0
198543,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,TA,...,37,47,42,0,0,0,0,0,0,0

In [99]:
races = r"RE_A|RE_B|RE_D|RE_F|RE_H|RE_I|RE_P|RE_T|RE_W"

In [100]:
dataframe8 = dataframe7[dataframe7['ReportingCategory'].str.contains(races, na=False)]

In [101]:
dataframe8

,AcademicYear,AggregateLevel,CountyCode,DistrictCode,SchoolCode,CountyName,DistrictName,SchoolName,Charter,ReportingCategory,...,GR_03,GR_04,GR_05,GR_06,GR_07,GR_08,GR_09,GR_10,GR_11,GR_12
195972,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_A,...,0,0,0,0,0,0,0,0,0,0
195973,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_B,...,0,0,0,0,0,0,0,0,0,0
195974,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_D,...,0,0,0,0,0,0,0,0,0,0
195975,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_F,...,0,0,0,0,0,0,0,0,0,0
195976,2023-24,S,38,68478.0,0.0,San Francisco,San Francisco Unified,District Office,N,RE_H,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198533,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_F,...,0,3,3,0,0,0,0,0,0,0
198534,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_H,...,22,20,18,0,0,0,0,0,0,0
198535,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_P,...,0,0,0,0,0,0,0,0,0,0
198536,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_T,...,2,1,2,0,0,0,0,0,0,0
198537,2023-24,S,38,68478.0,6115901.0,San Francisco,San Francisco Unified,Tenderloin Community,N,RE_W,...,1,8,2,0,0,0,0,0,0,0

In [102]:
unique_values = dataframe8['SchoolName'].unique()
unique_values

array(['District Office', 'Jordan (June) School for Equity',
       'Stockton (Commodore) Children Center', 'Noriega Children Center',
       'Tule Elk Park Children Center', 'McLaren (John) Children Centers',
       'S.F. International High', 'Academy (The)- SF @McAteer',
       'Chinese Immersion School at DeAvila',
       'San Francisco Public Montessori', 'Wells (Ida B.) High',
       'Downtown High', 'Independence High',
       'Wallenberg (Raoul) Traditional High',
       'Burton (Phillip and Sala) Academic High', 'Balboa High',
       'Asawa (Ruth) SF Sch of the Arts, A Public School',
       'Marshall (Thurgood) High', 'Galileo High',
       'Lincoln (Abraham) High', 'Lowell High', 'Mission High',
       "O'Connell (John) High", 'Washington (George) High',
       'Carmichael (Bessie)/FEC', 'Lawton Alternative',
       'Malcolm X Academy', 'Buena Vista/ Horace Mann K-8',
       'Lee (Edwin and Anita) Newcomer', 'Mission Education Center',
       'San Francisco Community Alternative',
       'Drew (Charles) College Preparatory Academy',
       'Tenderloin Community'], dtype=object)