In [2]:
import pandas as pd

def display_schools(file_path, output_path):
    """
    Reads a CSV file, filters out any rows where 'campus name' contains 'Lowell' or 'Ruth Awasa', 
    and writes to a new CSV file.
    :param file_path: Path to the CSV file.
    :param output_path: Path to save the filtered CSV file.
    """
    try:
        # Load the CSV file
        df = pd.read_csv('Schools_20250202.csv')
        
        # Ensure the column name is correct (update if necessary)
        if 'Campus Name' not in df.columns:
            raise ValueError("Column 'campus name' not found in CSV file. Please check the column names.")
        
        # Filter out schools where 'campus name' contains the excluded words
        excluded_keywords = ["Lowell", "Asawa"]
        filtered_df = df[~df['Campus Name'].str.contains('|'.join(excluded_keywords), case=False, na=False)]
        
        # Save to a new CSV file
        filtered_df.to_csv(output_path, index=False)
        
        # Display the remaining schools
        print(filtered_df)
        print(f"Filtered data has been saved to {output_path}")
    except Exception as e:
        print("Error:", e)

# Example usage
if __name__ == "__main__":
    csv_path = "Schools_20250202.csv"  # Path to your uploaded CSV file
    output_csv_path = "Filtered_Schools.csv"  # Path to save the new filtered CSV file
    display_schools(csv_path, output_csv_path)

                                           Campus Name CCSF Entity  \
0                   Milk, Harvey Milk Childrens Center       SFUSD
1                           Mckinley Elementary School       SFUSD
2    Jewish Community Center San Francisco - Rosenb...     Private
3                               Eureka Learning Center     Private
4                       Noriega Early Education School       SFUSD
..                                                 ...         ...
440                      Golden Gate Guppies Preschool     Private
441                                   Lands End School     Private
442                      San Francisco Pacific Academy     Private
443                    Wells, Ida B. Wells High School       SFUSD
444          Munchkinland Preschool And Family Daycare     Private

     Lower Grade  Upper Grade Grade Range               Category Map Label  \
0             -2           -1          PK               USD PreK    CDC095
1              0            5         K-5         USD Grades K-5     PS075
2             -2           -1          PK  Independent / Private    CDC058
3             -2           -1          PK  Independent / Private    CDC035
4             -2            5        PK-5          USD PreK/TK-5     PS085
..           ...          ...         ...                    ...       ...
440           -2           -1          PK  Independent / Private    CDC046
441           -2           -1          PK  Independent / Private    CDC071
442            0            8         K-8  Independent / Private    IND317
443            9           12        9-12        USD Grades 9-12     PS124
444           -2           -1          PK  Independent / Private    CDC110

     Lower Age  Upper Age General Type  ...  \
0            3          4          CDC  ...
1            5         10           PS  ...
2            3          4          CDC  ...
3            3          4          CDC  ...
4            3         10           PS  ...
..         ...        ...          ...  ...
440          3          4          CDC  ...
441          3          4          CDC  ...
442          5         13          IND  ...
443         14         17           PS  ...
444          3          4          CDC  ...

                                        Campus Address Supervisor District  \
0                 841 ELLIS ST, SAN FRANCISCO CA 94117                   6
1                1025 14TH ST, San Francisco, CA 94114                   8
2           325 ARGUELLO BLVD, SAN FRANCISCO, CA 94118                   1
3              464 DIAMOND ST, SAN FRANCISCO, CA 94114                   8
4               1775 44TH AVE, San Francisco, CA 94122                   4
..                                                 ...                 ...
440        2426 CALIFORNIA ST, SAN FRANCISCO, CA 94115                   2
441  4150 CLEMENT ST BLDG T35, SAN FRANCISCO, CA 94121                   1
442            3301 BALBOA ST, SAN FRANCISCO, CA 94121                   1
443             1099 HAYES ST, SAN FRANCISCO, CA 94117                   5
444          4710 CABRILLO ST, SAN FRANCISCO, CA 94121                   1

     County FIPS    County Name                    Location 1  \
0           6075  SAN FRANCISCO  CA\n(37.783802, -122.420105)
1           6075  SAN FRANCISCO  CA\n(37.766884, -122.436279)
2           6075  SAN FRANCISCO  CA\n(37.784588, -122.459488)
3           6075  SAN FRANCISCO  CA\n(37.754967, -122.437004)
4           6075  SAN FRANCISCO  CA\n(37.753834, -122.503654)
..           ...            ...                           ...
440         6075  SAN FRANCISCO  CA\n(37.789124, -122.434509)
441         6075  SAN FRANCISCO  CA\n(37.782593, -122.504578)
442         6075  SAN FRANCISCO  CA\n(37.775639, -122.494286)
443         6075  SAN FRANCISCO  CA\n(37.775013, -122.433899)
444         6075  SAN FRANCISCO  CA\n(37.773445, -122.509254)

    Neighborhoods (old)  Zip Codes  Fire Prevention Districts  \
0                    36      28858                        7.0
1                     3      28862                       15.0
2                    11         54                       11.0
3                    22      28862                        2.0
4                    35         56                        1.0
..                  ...        ...                        ...
440                  27      29490                       13.0
441                  15         55                       11.0
442                  26         55                       11.0
443                  10      29492                       15.0
444                  26         55                       11.0

     Police Districts  Supervisor Districts
0                 9.0                     9
1                 5.0                     5
2                 6.0                     2
3                 4.0                     5
4                 8.0                     3
..                ...                   ...
440               9.0                     1
441               6.0                     2
442               6.0                     2
443               5.0                    11
444               6.0                     2

[443 rows x 21 columns]
Filtered data has been saved to Filtered_Schools.csv

In [3]:
import geopandas as gpd
import folium
from geopy.distance import geodesic

In [4]:
Filtered = gpd.read_file('Filtered_Schools.csv')

In [5]:
Filtered.head()

,Campus Name,CCSF Entity,Lower Grade,Upper Grade,Grade Range,Category,Map Label,Lower Age,Upper Age,General Type,...,Campus Address,Supervisor District,County FIPS,County Name,Location 1,Neighborhoods (old),Zip Codes,Fire Prevention Districts,Police Districts,Supervisor Districts
0,"Milk, Harvey Milk Childrens Center",SFUSD,-2,-1,PK,USD PreK,CDC095,3,4,CDC,...,"841 ELLIS ST, SAN FRANCISCO CA 94117",6,6075,SAN FRANCISCO,"CA\n(37.783802, -122.420105)",36,28858,7.0,9.0,9
1,Mckinley Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS075,5,10,PS,...,"1025 14TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.766884, -122.436279)",3,28862,15.0,5.0,5
2,Jewish Community Center San Francisco - Rosenb...,Private,-2,-1,PK,Independent / Private,CDC058,3,4,CDC,...,"325 ARGUELLO BLVD, SAN FRANCISCO, CA 94118",1,6075,SAN FRANCISCO,"CA\n(37.784588, -122.459488)",11,54,11.0,6.0,2
3,Eureka Learning Center,Private,-2,-1,PK,Independent / Private,CDC035,3,4,CDC,...,"464 DIAMOND ST, SAN FRANCISCO, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.754967, -122.437004)",22,28862,2.0,4.0,5
4,Noriega Early Education School,SFUSD,-2,5,PK-5,USD PreK/TK-5,PS085,3,10,PS,...,"1775 44TH AVE, San Francisco, CA 94122",4,6075,SAN FRANCISCO,"CA\n(37.753834, -122.503654)",35,56,1.0,8.0,3

In [6]:
publicschools = Filtered[Filtered['CCSF Entity'].str.contains('SFUSD')]

In [7]:
publicschools

,Campus Name,CCSF Entity,Lower Grade,Upper Grade,Grade Range,Category,Map Label,Lower Age,Upper Age,General Type,...,Campus Address,Supervisor District,County FIPS,County Name,Location 1,Neighborhoods (old),Zip Codes,Fire Prevention Districts,Police Districts,Supervisor Districts
0,"Milk, Harvey Milk Childrens Center",SFUSD,-2,-1,PK,USD PreK,CDC095,3,4,CDC,...,"841 ELLIS ST, SAN FRANCISCO CA 94117",6,6075,SAN FRANCISCO,"CA\n(37.783802, -122.420105)",36,28858,7.0,9.0,9
1,Mckinley Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS075,5,10,PS,...,"1025 14TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.766884, -122.436279)",3,28862,15.0,5.0,5
4,Noriega Early Education School,SFUSD,-2,5,PK-5,USD PreK/TK-5,PS085,3,10,PS,...,"1775 44TH AVE, San Francisco, CA 94122",4,6075,SAN FRANCISCO,"CA\n(37.753834, -122.503654)",35,56,1.0,8.0,3
10,Sutro Elementary / Early Education,SFUSD,0,5,K-5,USD Grades K-5,PS113,5,10,PS,...,"235 12TH AVE, San Francisco, CA 94118",1,6075,SAN FRANCISCO,"CA\n(37.783604, -122.471451)",11,54,11.0,6.0,2
11,"Marshall, Thurgood Marshall High School",SFUSD,9,12,9-12,USD Grades 9-12,PS073,14,17,PS,...,"45 CONKLING ST, San Francisco, CA 94124",10,6075,SAN FRANCISCO,"CA\n(37.736309, -122.401649)",1,58,10.0,3.0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,Longfellow Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS068,5,10,PS,...,"755 MORSE ST, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.710423, -122.446739)",5,28861,9.0,7.0,6
435,"Webster, Daniel Webster Out-Of-School (OST) Pr...",SFUSD,0,5,K-5,USD Grades K-5,PS123,5,10,PS,...,"465 MISSOURI ST, San Francisco, CA 94107",10,6075,SAN FRANCISCO,"CA\n(37.760521, -122.395843)",29,28856,10.0,3.0,8
436,Mission High School,SFUSD,9,12,9-12,USD Grades 9-12,PS080,14,17,PS,...,"3750 18TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.76202, -122.427307)",3,28862,8.0,4.0,5
437,Miraloma Elementary School,SFUSD,0,5,K-5,USD Grades K-5,PS078,5,10,PS,...,"175 OMAR WAY, San Francisco, CA 94127",7,6075,SAN FRANCISCO,"CA\n(37.738636, -122.450188)",40,59,9.0,7.0,4
441,"Wells, Ida B. Wells High School",SFUSD,9,12,9-12,USD Grades 9-12,PS124,14,17,PS,...,"1099 HAYES ST, SAN FRANCISCO, CA 94117",5,6075,SAN FRANCISCO,"CA\n(37.775013, -122.433899)",10,29492,15.0,5.0,11

In [8]:
publichighschools = publicschools[publicschools['Grade Range'].str.contains('9-12')]

In [9]:
publichighschools

,Campus Name,CCSF Entity,Lower Grade,Upper Grade,Grade Range,Category,Map Label,Lower Age,Upper Age,General Type,...,Campus Address,Supervisor District,County FIPS,County Name,Location 1,Neighborhoods (old),Zip Codes,Fire Prevention Districts,Police Districts,Supervisor Districts
11,"Marshall, Thurgood Marshall High School",SFUSD,9,12,9-12,USD Grades 9-12,PS073,14,17,PS,...,"45 CONKLING ST, San Francisco, CA 94124",10,6075,SAN FRANCISCO,"CA\n(37.736309, -122.401649)",1,58,10.0,3.0,8
38,"Hearst, Phoebe Apperson Hearst Home",SFUSD,9,12,9-12,USD Grades 9-12,PS045,14,17,PS,...,"3045 SANTIAGO ST, SAN FRANCISCO 94116",4,6075,SAN FRANCISCO,"CA\n(37.74363, -122.500053)",35,29491,1.0,8.0,3
90,"Burton, Phillip And Sala Burton High School",SFUSD,9,12,9-12,USD Grades 9-12,PS011,14,17,PS,...,"400 MANSELL ST, San Francisco, CA 94134",9,6075,SAN FRANCISCO,"CA\n(37.721546, -122.406555)",28,309,10.0,3.0,7
92,"Washington, George Washington High School",SFUSD,9,12,9-12,USD Grades 9-12,PS121,14,17,PS,...,"600 32ND AVE, San Francisco, CA 94121",1,6075,SAN FRANCISCO,"CA\n(37.777905, -122.491013)",26,55,11.0,6.0,2
135,"Lincoln, Abraham Lincoln High School",SFUSD,9,12,9-12,USD Grades 9-12,PS067,14,17,PS,...,"2162 24TH AVE, San Francisco, CA 94116",4,6075,SAN FRANCISCO,"CA\n(37.746594, -122.48024)",35,29491,1.0,8.0,3
174,Life Learning Academy Charter School,SFUSD,9,12,9-12,USD Charter School,PS064,14,17,PS,...,"651 8TH TI ST, SAN FRANCISCO, CA 94130",6,6075,SAN FRANCISCO,"CA\n(37.825512, -122.367996)",37,62,,2.0,9
194,Gateway High School / Kipp Sf Bay Academy,SFUSD,9,12,9-12,USD Charter School,PS037,14,17,PS,...,"1430 SCOTT ST, San Francisco, CA 94115",5,6075,SAN FRANCISCO,"CA\n(37.783264, -122.436691)",41,29490,13.0,5.0,11
195,Galileo High School,SFUSD,9,12,9-12,USD Grades 9-12,PS035,14,17,PS,...,"1150 FRANCISCO ST, San Francisco, CA 94109",2,6075,SAN FRANCISCO,"CA\n(37.803791, -122.424149)",32,28858,5.0,9.0,1
219,Balboa High School,SFUSD,9,12,9-12,USD Grades 9-12,PS007,14,17,PS,...,"1000 CAYUGA AVE, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.721142, -122.441399)",25,28861,9.0,7.0,6
284,City Arts And Tech High School,SFUSD,9,12,9-12,USD Grades 9-12,PS019,14,17,PS,...,"325 LA GRANDE AVE, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.718784, -122.424667)",18,309,9.0,7.0,6
286,Independence High School,SFUSD,9,12,9-12,USD Grades 9-12,PS049,14,17,PS,...,"1350 07TH AVE, San Francisco, CA 94122",5,6075,SAN FRANCISCO,"CA\n(37.763226, -122.463585)",12,56,1.0,5.0,11
305,"Wallenberg, Raoul Wallenberg High School",SFUSD,9,12,9-12,USD Grades 9-12,PS120,14,17,PS,...,"40 VEGA ST, San Francisco, CA 94118",2,6075,SAN FRANCISCO,"CA\n(37.780647, -122.445953)",16,54,15.0,5.0,1
328,Downtown High School,SFUSD,9,12,9-12,USD Grades 9-12,PS025,14,17,PS,...,"693 VERMONT ST, San Francisco, CA 94107",10,6075,SAN FRANCISCO,"CA\n(37.761398, -122.403702)",29,28856,10.0,3.0,8
331,San Francisco International High School,SFUSD,9,12,9-12,USD Grades 9-12,PS101,14,17,PS,...,"1050 YORK ST, SAN FRANCISCO, CA 94110",9,6075,SAN FRANCISCO,"CA\n(37.75523, -122.408859)",19,28859,2.0,4.0,7
414,"Jordan, June Jordan High School",SFUSD,9,12,9-12,USD Grades 9-12,PS053,14,17,PS,...,"325 LA GRANDE AVE, San Francisco, CA 94112",11,6075,SAN FRANCISCO,"CA\n(37.719536, -122.425148)",18,309,9.0,7.0,6
417,"O'Connell, John O'Connell High School",SFUSD,9,12,9-12,USD Grades 9-12,PS086,14,17,PS,...,"2355 FOLSOM ST, San Francisco, CA 94110",9,6075,SAN FRANCISCO,"CA\n(37.759514, -122.413559)",19,28859,2.0,4.0,7
436,Mission High School,SFUSD,9,12,9-12,USD Grades 9-12,PS080,14,17,PS,...,"3750 18TH ST, San Francisco, CA 94114",8,6075,SAN FRANCISCO,"CA\n(37.76202, -122.427307)",3,28862,8.0,4.0,5
441,"Wells, Ida B. Wells High School",SFUSD,9,12,9-12,USD Grades 9-12,PS124,14,17,PS,...,"1099 HAYES ST, SAN FRANCISCO, CA 94117",5,6075,SAN FRANCISCO,"CA\n(37.775013, -122.433899)",10,29492,15.0,5.0,11

In [10]:
stops = gpd.read_file('Muni_Stops_20250126.csv')

In [11]:
stops.head()

,OBJECTID,STOPNAME,TRAPEZESTOPABBR,RUCUSSTOPABBR,STOPID,LATITUDE,LONGITUDE,ACCESSIBILITYMASK,ATSTREET,ONSTREET,...,SIGNUPID,SUPERVISOR_DISTRICT,shape,data_as_of,data_loaded_at,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods,Neighborhoods,SF Find Neighborhoods
0,72869,17th St&Noe St *-MI,17ST.NO0,17ST.NOE,3318,37.762645,-122.432991,,NOE ST,17TH ST,...,147,8,POINT (-122.432991 37.762645),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,3,5,5,38,38
1,73624,Judah St&12th Ave NE-NS/SI,JUDA12A0,JUDA12AV,5195,37.762069,-122.469324,1,12TH AVE,JUDAH ST,...,147,7,POINT (-122.469324 37.762069),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,10,11,14,109,109
2,73681,Mansell St&Somerset St S-NS/PS,MANSSOM0,MANSSOME,5351,37.720417999999995,-122.40509399999999,,SOMERSET ST,MANSELL ST,...,147,9,POINT (-122.405094 37.720418),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,2,9,25,75,75
3,74029,Mission St&Sickles Ave W-FS/BZ,MISSSIC0,MISSSICK,5619,37.70866,-122.45331999999999,,SICKLES AVE,MISSION ST,...,147,11,POINT (-122.45332 37.70866),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,9,1,28,66,66
4,75912,Ulloa St&14th Ave SW-NS/PS,ULOA14S1,ULOA14AV,8137,37.741355999999996,-122.470211,,14TH AVE,ULLOA ST,...,147,7,POINT (-122.470211 37.741356),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,10,8,41,46,46

In [12]:
routes = gpd.read_file('Muni_Simple_Routes_20250202.csv')

In [13]:
routes.head()

,objectid,PATTERN,PATTERNID,ROUTE_NAME,DIRECTION,PATTERN_TYPE,SUB_TYPE,PATTERN_VERSION,LINEABBR,SIGNID,SERVICE_CA,shape,data_as_of,data_loaded_at
0,13796,1 I F00,216532,1,I,F,0,0,001,147,Frequent Local,"MULTILINESTRING ((-122.493147 37.779708, -122....",11/02/2024 08:47:18 PM,11/04/2024 09:42:45 AM
1,13797,1 O F00,216528,1,O,F,0,0,001,147,Frequent Local,"MULTILINESTRING ((-122.396968 37.795436, -122....",11/02/2024 08:47:18 PM,11/04/2024 09:42:45 AM
2,13798,12 I F10,216605,12,I,F,1,0,012,147,Grid,"MULTILINESTRING ((-122.420282 37.74802, -122.4...",11/02/2024 08:47:18 PM,11/04/2024 09:42:45 AM
3,13799,12 O F10,216602,12,O,F,1,0,012,147,Grid,"MULTILINESTRING ((-122.423061 37.79394, -122.4...",11/02/2024 08:47:18 PM,11/04/2024 09:42:45 AM
4,13800,14 I F00,216612,14,I,F,0,0,014,147,Frequent Local,"MULTILINESTRING ((-122.459906 37.706479, -122....",11/02/2024 08:47:18 PM,11/04/2024 09:42:45 AM

In [14]:
# Function to calculate distance between two coordinates
def calculate_distance(coord1, coord2):
    return geodesic(coord1, coord2).miles

In [15]:
# Function to extract and clean coordinates from the 'Location 1' field
def extract_coordinates(location):
    try:
        # Assuming the location is a string of format "CA\n(latitude, longitude)"
        parts = location.split('(')[1].strip(')').split(',')
        # Convert to float and return as a tuple
        return float(parts[0]), float(parts[1])
    except (ValueError, IndexError):
        # If conversion fails, return None
        return None

In [16]:
# Filter stops within 0.25 miles of any school
filtered_stops = []

for stop_idx, stop_row in stops.iterrows():
    stop_coord = (stop_row['LATITUDE'], stop_row['LONGITUDE'])
    for school_idx, school_row in publichighschools.iterrows():
        # Extract school coordinates
        school_coord = extract_coordinates(school_row['Location 1'])
        if school_coord:
            # Calculate distance
            distance = calculate_distance(stop_coord, school_coord)
            if distance <= 0.25:
                filtered_stops.append(stop_row)
                break

In [17]:
filtered_stops_df = pd.DataFrame(filtered_stops)

In [18]:
sf_map = folium.Map(location=[37.7749, -122.4194], zoom_start=12)

In [19]:
for idx, row in routes.iterrows():
    # Extract the route shape from the 'shape' column
    shape = row['shape'].replace('MULTILINESTRING ((', '').replace('))', '')
    points = shape.split(', ')
    coordinates = [(float(point.split()[1]), float(point.split()[0])) for point in points]
    
    folium.PolyLine(
        coordinates,
        color='red',
        weight=2.5,
        opacity=1
    ).add_to(sf_map)

In [20]:
# Add filtered Muni stops to the map
for idx, row in filtered_stops_df.iterrows():
    folium.CircleMarker(
        location=[row['LATITUDE'], row['LONGITUDE']],
        radius=3,  # Radius of the circle marker
        color='blue',  # Border color of the circle marker
        fill=True,  # Fill the circle marker
        fill_color='blue'  # Fill color of the circle marker
    ).add_to(sf_map)

In [21]:
# Add schools to the map with red color
for idx, row in publichighschools.iterrows():
    school_coord = extract_coordinates(row['Location 1'])
    if school_coord:
        folium.CircleMarker(
            location=school_coord,
            radius=3,  # Radius of the circle marker
            color='green',  # Border color of the circle marker
            fill=True,  # Fill the circle marker
            fill_color='green',  # Fill color of the circle marker
            popup=row['Campus Name']  # Popup with school name
        ).add_to(sf_map)

In [22]:
sf_map.save('sf_muni_map.html')

In [23]:
sf_map

In [24]:
filtered_stops_df

,OBJECTID,STOPNAME,TRAPEZESTOPABBR,RUCUSSTOPABBR,STOPID,LATITUDE,LONGITUDE,ACCESSIBILITYMASK,ATSTREET,ONSTREET,...,SIGNUPID,SUPERVISOR_DISTRICT,shape,data_as_of,data_loaded_at,Current Police Districts,Current Supervisor Districts,Analysis Neighborhoods,Neighborhoods,SF Find Neighborhoods
2,73681,Mansell St&Somerset St S-NS/PS,MANSSOM0,MANSSOME,5351,37.720417999999995,-122.40509399999999,,SOMERSET ST,MANSELL ST,...,147,9,POINT (-122.405094 37.720418),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,2,9,25,75,75
5,75443,Hayes St&Pierce St SE-FS/BZ,HAYSPIE1,HAYSPIER,5004,37.775413,-122.434177,,PIERCE ST,HAYES ST,...,147,5,POINT (-122.434177 37.775413),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,4,11,9,23,23
29,73138,Church St&18TH St NW-NS/SI,CHUR18S0,CHUR18ST,3987,37.761466999999996,-122.428416,,18TH ST,CHURCH ST,...,147,8,POINT (-122.428416 37.761467),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,3,5,5,37,37
41,75603,Parnassus Ave&4th Ave NE-NS/BZ,PARN 4A0,PARN 4AV,5885,37.762727,-122.46074,,4TH AVE,PARNASSUS AVE,...,147,7,POINT (-122.46074 37.762727),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,7,11,14,109,109
52,74233,Presidio Ave&Geary Blvd NE-FS/BZ,PRESGEA1,PRESGEAR,6092,37.782706,-122.445796,,GEARY BLVD,PRESIDIO AVE,...,147,2,POINT (-122.445796 37.782706),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,8,6,31,103,103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,73136,Church St&16TH St SE-NS/SI,CHUR16S1,CHUR16ST,3985,37.764382,-122.428609,,16TH ST,CHURCH ST,...,147,8,POINT (-122.428609 37.764382),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,3,5,5,37,37
3218,74976,Sutter St&Steiner St SW-NS/BZ,SUTTSTE1,SUTTSTEI,6610,37.785793999999996,-122.435028,,STEINER ST,SUTTER ST,...,147,5,POINT (-122.435028 37.785794),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,4,11,15,103,103
3227,72793,18th St&Sanchez St NE-NS/BZ,18STSNC1,18STSNCZ,3344,37.761227999999996,-122.430464,,SANCHEZ ST,18TH ST,...,147,8,POINT (-122.430464 37.761228),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,3,5,5,37,37
3260,75399,Judah St&5th Ave SW-NS/PS,JUDA 5A1,JUDA 5AV,5189,37.762299,-122.462001,,5TH AVE,JUDAH ST,...,147,7,POINT (-122.462001 37.762299),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,7,11,14,109,109
3271,75191,Sutter St&Steiner St NE-NS/BZ,SUTTSTE0,SUTTSTEI,6609,37.785942,-122.434793,,STEINER ST,SUTTER ST,...,147,5,POINT (-122.434793 37.785942),11/02/2024 08:47:21 PM,11/04/2024 09:42:39 AM,4,11,30,103,103

In [25]:
route2df = pd.read_csv('routes.txt')

In [26]:
route2df

,route_id,agency_id,route_short_name,route_long_name,route_url,route_desc,route_type,route_color,route_text_color,route_sort_order
0,1,SFMTA,1,CALIFORNIA,https://SFMTA.com/1,5am-12 midnight daily,3,005B95,FFFFFF,NaN
1,12,SFMTA,12,FOLSOM-PACIFIC,https://SFMTA.com/12,6am-10pm daily,3,005B95,FFFFFF,NaN
2,14,SFMTA,14,MISSION,https://SFMTA.com/14,24 hour service daily,3,005B95,FFFFFF,NaN
3,14R,SFMTA,14R,MISSION RAPID,https://SFMTA.com/14R,5am-10pm daily,3,BF2B45,FFFFFF,NaN
4,15,SFMTA,15,BAYVIEW HUNTERS POINT EXPRESS,https://SFMTA.com/15,Weekdays 5am-10pm Weekends 8am-10pm,3,005B95,FFFFFF,NaN
...,...,...,...,...,...,...,...,...,...,...
64,T,SFMTA,T,THIRD,https://SFMTA.com/T,Weekends 8 am-11:30 pm,0,BF2B45,FFFFFF,NaN
65,TBUS,SFMTA,TBUS,THIRD BUS,https://SFMTA.com/TBUS,Weekdays 5am-6am Weekends 5am-8am,3,BF2B45,FFFFFF,NaN
66,FBUS,SFMTA,FBUS,MARKET & WHARVES,http://www.sfmta.com/FBUS,NaN,0,B49A36,000000,NaN
67,L,SFMTA,L,TARAVAL,https://SFMTA.com/L,5am-10 pm daily,0,942D83,FFFFFF,NaN
68,30X,SFMTA,30X,MARINA EXPRESS,http://www.sfmta.com/30X,7 am-9 am Weekdays,3,005B95,FFFFFF,NaN

In [28]:
trips2 = pd.read_csv('trips.txt')
trips2

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,1,1,11708204,Geary + 33rd Avenue,0,102,217842,1,1
1,1,1,11708205,Geary + 33rd Avenue,0,104,217842,1,1
2,1,1,11708206,Geary + 33rd Avenue,0,106,217842,1,1
3,1,1,11708207,Geary + 33rd Avenue,0,107,217842,1,1
4,1,1,11708208,Geary + 33rd Avenue,0,101,217841,1,1
...,...,...,...,...,...,...,...,...,...
25528,TBUS,3,11741271,Visitacion Valley,1,912,218359,1,1
25529,TBUS,3,11741272,Visitacion Valley,1,1505,218359,1,1
25530,TBUS,3,11741273,Visitacion Valley,1,2909,218359,1,1
25531,TBUS,3,11741274,Visitacion Valley,1,1503,218359,1,1
25532,TBUS,3,11741275,Visitacion Valley,1,1501,218360,1,1

In [29]:
stoptimes = pd.read_csv('stop_times.txt')
stoptimes

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,shape_dist_traveled
0,11708204,04:32:00,04:32:00,3892,30,,,,
1,11708204,04:32:40,04:32:40,3875,31,,,,
2,11708204,04:33:28,04:33:28,3896,32,,,,
3,11708204,04:34:13,04:34:13,3852,33,,,,
4,11708204,04:34:46,04:34:46,3845,34,,,,
...,...,...,...,...,...,...,...,...,...
961716,11756028,07:55:59,07:55:59,6619,12,,,,
961717,11756028,07:57:00,07:57:00,6617,13,,,,
961718,11756028,07:58:14,07:58:14,6615,14,,,,
961719,11756028,08:00:53,08:00:53,8137,15,,,,
961720,11756028,08:03:00,08:03:00,6744,16,,,,

In [36]:
stopslist = filtered_stops_df['STOPID'].tolist()
stopslist

['5351',
 '5004',
 '3987',
 '5885',
 '6092',
 '5988',
 '6979',
 '6213',
 '7857',
 '3480',
 '4435',
 '6082',
 '7983',
 '3454',
 '5094',
 '5469',
 '7996',
 '5782',
 '3745',
 '6724',
 '6420',
 '5615',
 '5060',
 '3216',
 '5301',
 '5920',
 '7732',
 '6636',
 '3551',
 '5609',
 '4474',
 '6723',
 '7911',
 '3984',
 '5718',
 '5464',
 '4492',
 '3743',
 '4491',
 '7248',
 '3763',
 '3057',
 '3217',
 '3759',
 '4811',
 '4357',
 '7638',
 '3744',
 '5341',
 '6424',
 '4271',
 '7067',
 '7733',
 '6635',
 '6142',
 '3738',
 '5352',
 '3557',
 '6590',
 '6093',
 '5909',
 '5883',
 '6972',
 '3558',
 '6275',
 '3565',
 '7953',
 '5867',
 '4765',
 '3473',
 '7912',
 '4991',
 '6716',
 '6084',
 '6143',
 '4616',
 '3093',
 '7984',
 '4675',
 '5992',
 '4432',
 '6710',
 '5459',
 '7836',
 '5598',
 '4414',
 '6085',
 '5012',
 '3552',
 '3211',
 '5003',
 '3559',
 '5296',
 '5709',
 '6634',
 '7999',
 '3564',
 '6637',
 '5699',
 '4295',
 '5990',
 '6419',
 '3330',
 '5987',
 '3323',
 '5343',
 '5339',
 '3747',
 '5698',
 '5719',
 '5337',
 '6632',
 '5080',
 '4415',
 '3957',
 '6203',
 '3331',
 '3739',
 '5297',
 '6978',
 '4291',
 '3742',
 '5011',
 '6820',
 '3758',
 '3060',
 '913',
 '3735',
 '5884',
 '6083',
 '7909',
 '4278',
 '6144',
 '3737',
 '6800',
 '5096',
 '5401',
 '3388',
 '4761',
 '4960',
 '3283',
 '4621',
 '5400',
 '7908',
 '5710',
 '4277',
 '3474',
 '6711',
 '6192',
 '4634',
 '5342',
 '5192',
 '3334',
 '7288',
 '6037',
 '5081',
 '3059',
 '4672',
 '4760',
 '3553',
 '4993',
 '5915',
 '3764',
 '7687',
 '6038',
 '5991',
 '3054',
 '4810',
 '3308',
 '6395',
 '6722',
 '5908',
 '3214',
 '4273',
 '5800',
 '8031',
 '7926',
 '4961',
 '5472',
 '5804',
 '6801',
 '4614',
 '6806',
 '4632',
 '4487',
 '6608',
 '3322',
 '5340',
 '4758',
 '3345',
 '5194',
 '6607',
 '5703',
 '6145',
 '5921',
 '4622',
 '3055',
 '5059',
 '4633',
 '4354',
 '3285',
 '5338',
 '4615',
 '5805',
 '5191',
 '3986',
 '5599',
 '3734',
 '3740',
 '4426',
 '6819',
 '5067',
 '7529',
 '5095',
 '4352',
 '5344',
 '3741',
 '8128',
 '3767',
 '4294',
 '6725',
 '6191',
 '3284',
 '3389',
 '6971',
 '7910',
 '4434',
 '4293',
 '4279',
 '3221',
 '4631',
 '4845',
 '4272',
 '6034',
 '6204',
 '3762',
 '6119',
 '3458',
 '4964',
 '8032',
 '3459',
 '6717',
 '6147',
 '4431',
 '3746',
 '5193',
 '3215',
 '3220',
 '3554',
 '4994',
 '5914',
 '3333',
 '3053',
 '3213',
 '5014',
 '4275',
 '5468',
 '4488',
 '3560',
 '4617',
 '6039',
 '4671',
 '6274',
 '4274',
 '6193',
 '4422',
 '4992',
 '3056',
 '4421',
 '5783',
 '4289',
 '6589',
 '3550',
 '4425',
 '5906',
 '4353',
 '5907',
 '6146',
 '7837',
 '5190',
 '6195',
 '3229',
 '3736',
 '3453',
 '6633',
 '4290',
 '3058',
 '7476',
 '3985',
 '6610',
 '3344',
 '5189',
 '6609']

In [37]:
stoptimesatbus = stoptimes[stoptimes['stop_id'].isin(stopslist)]

In [38]:
stoptimesatbus

Empty DataFrame
Columns: [trip_id, arrival_time, departure_time, stop_id, stop_sequence, stop_headsign, pickup_type, drop_off_type, shape_dist_traveled]
Index: []